### ISSUE TITLE
rubocop linting

### ISSUE THREAD

**Issue by gurgeous** [postmodern/command_kit.rb#34]
Let's add it! You can see first steps here - https://github.com/postmodern/command_kit.rb/compare/main...gurgeous:rubocop?expand=1

I used `rubocop --auto-gen-config` to create a starter config. The config disables rules that conflict with the current code. In other words, running rubocop autocorrect will produce zero changes. I created a [preview gist](https://gist.github.com/gurgeous/4bfed3a0ae973faa0d68e8cd28dd4562) that shows how enabling each rule would affect the source. It's not exactly meant for reading, but you can search in there to see how each rule works.

We can use editorial discretion to turn on some rules. It's totally up to you, but I'd suggest enabling some. Let rubocop do work for us. For example, see `DuplicateMethods, MutableConstant, or UselessAssignment`. Could be real bugs in there. I'd also suggest turning on rules to enforce our preferred style if possible. For example, consider `Style/StringLiterals: { EnforcedStyle: double_quotes }`.

What do you think? Would you like me to recommend specific rules?

**Comment by postmodern** [comment]
Awesome!

I reviewed the list of 1 or 2 violations, and fixed the following:

* DuplicatedAssignment
* ElseAlignment
* EndAlignment
* IndentationWidth
* DuplicateMethods
* UselessAssignment
* Encoding
* RedundantBegin
* RedundantInterpolation
* TrailingCommaInArrayLiteral

The following rules might just need exclusions:

* RescueException (exclude lib/command_kit/exception_handler.rb:42)
* UnreachableLoop (exclude lib/command_kit/interactive.rb:129)
* QuotedSymbols (exclude spec/inflector_spec.rb:26)
* RedundantException (exclude spec/exception_handler_spec.rb:76)

I will need to refactor `Inflector.camel_case` to get rid of `UnusedBlockArgument` (also not happy with using `Regexp.last_match`).

`RedundantRegexpEscape` referring to `lib/command_kit/commands/subcommand.rb:59` looks invalid (the regexp is supposed to match all non-`.` characters starting at the beginning of the first line).

I couldn't easily fix `MissingSuper` in `lib/command_kit/commands/auto_load.rb:76`, as adding `super()` caused two specs to fail with:

```
     TypeError:
       no implicit conversion of nil into String
     # ./lib/command_kit/commands/auto_load.rb:141:in `join'
     # ./lib/command_kit/commands/auto_load.rb:141:in `join'
     # ./lib/command_kit/commands/auto_load.rb:124:in `command'
     # ./spec/commands/auto_load_spec.rb:34:in `block (5 levels) in <top (required)>'
     # ./lib/command_kit/commands/auto_load.rb:77:in `initialize'
     # ./lib/command_kit/commands/auto_load.rb:77:in `initialize'
     # ./spec/commands/auto_load_spec.rb:33:in `new'
     # ./spec/commands/auto_load_spec.rb:33:in `block (4 levels) in <top (required)>'
     # ./spec/commands/auto_load_spec.rb:40:in `block (4 levels) in <top (required)>'
```

**Comment by gurgeous** [comment]
Great start! I merged your fixes into my branch. Few comments - 

1. In case you haven't tried it, `rubocop -A` will autocorrect the majority of issues. When we decide to adopt a rule, often you can do it without manual changes.
2. UnreachableLoop - Took a quick peek. Is there any need for the loop? As rubocop said, it seems to only run once. My personal code golf would probably produce `answer = ask(...) ; !!(answer =~ /^y/i)` or similar 😛 
3. QuotedSymbols - We can tell rubocop to always use double quotes
4. RedundantException - Can we just `raise "error"` ?
5. RedundantRegexpEscape - I think no backslash required for dot inside `[xxxx]`
6. MissingSuper - No clue on this one. I like the rule, though. It's saved me from bugs in the past. It's possible to get around stuff like this with rubocop comments if we decide to turn on the rule.

I know rubocop can be a pain, sorry. The nice thing about building a decent .rubocop.yml is that you can reuse it across projects and enforce your desired style everywhere.

How should I proceed? I can tell you are having fun with this and I don't want to step on your toes 😄

**Comment by postmodern** [comment]
> 2. UnreachableLoop - Took a quick peek. Is there any need for the loop? As rubocop said, it seems to only run once. My personal code golf would probably produce answer = ask(...) ; !!(answer =~ /^y/i) or similar ￼

The loop is used to re-print the input prompt if the user entered an invalid answer, or if they just hit `<enter>` and a response is required.

> 3. QuotedSymbols - We can tell rubocop to always use double quotes

See the offending spec. I suppose it could be rewritten as `"Foo::Bar".to_sym`. Also I think `:"foo"` syntax is useful for when you want to define a symbol that contains spaces or other non-alpha-numeric characters.

> 4. RedundantException - Can we just raise "error" ?

Uh sure. Although I kind of like specifying the exception class explicitly, even when it's `RuntimeError`.

> 5. RedundantRegexpEscape - I think no backslash required for dot inside [xxxx]

Ah I think you're right. However, I would argue that you should always escape `.` within a regexp, even inside a `[ ]` range, as `.` is normally interpreted as any-char.

As long as we can disable the pedantic or annoying rubocop rules, I'm fine with rebasing and merging it. It will help automate away some of the code review work.

**Comment by gurgeous** [comment]
> The loop is used to re-print the input prompt if the user entered an invalid answer, or if they just hit `<enter>` and a response is required (ex: `ask("Must answer", required: true)`).

I think I see the confusion. Look at line 129 (not line 199) 😄


> > 1. QuotedSymbols - We can tell rubocop to always use double quotes
> 
> See the offending spec. I suppose it could be rewritten as `"Foo::Bar".to_sym`. Also I think `:"foo"` syntax is useful for when you want to define a symbol that contains spaces or other non-alpha-numeric characters.

I believe rubocop wants to change it to `:'Foo::Bar'` (single quote). We can have it format with double quotes if you want, though.


> > 1. RedundantException - Can we just raise "error" ?
> 
> Uh sure. Although I kind of like specifying the exception class explicitly, even when it's `RuntimeError`.

There are a lot of fringe rubocop rules like this... We can just turn rules off whenever we have a stylistic preference. Here's [an example](https://github.com/gurgeous/httpdisk/blob/main/.rubocop.yml) from one of my other projects.



> 
> > 1. RedundantRegexpEscape - I think no backslash required for dot inside [xxxx]
> 
> Ah I think you're right. However, I would argue that you should always escape `.` within a regexp, even inside a `[ ]` range, as `.` is normally interpreted as any-char.

Regex is a dark art and I have no objection to leaving in the backslashes.

> 
> As long as we can disable the pedantic or annoying rubocop rules, I'm fine with rebasing and merging it. It will help automate away some of the code review work.

Sounds good. I'll try to re-enable the rules that you fixed and put up a PR. I usually just use github's squash and merge button in lieu of a rebase... You can make that the default for the repo if you want, I think. Happy to rebase manually if you prefer that. Just LMK

Thanks @postmodern this is great!

**Comment by postmodern** [comment]
Quick question. I'm a little worried about using `-A` to auto-fix issues. Wouldn't this cause issues if we added `bundle exec rake rubocop` to the GitHub Actions CI pipeline and a contributor sent a malformed PR? We'd probably want to flag but not auto-correct the PR.

**Comment by gurgeous** [comment]
Good question, I'm leery of that too. Linting is nice but it feels wrong to have it break CI IMO. I've used these a couple of different approaches in the past:
 
1. Precommit hook (bail if anything chages). This is good for projects where you can enforce a convention.
2. Run on `rake release` (bail if anything changes). This is good for gems. As a maintainer I just get in the habit of running rake rubocop occasionally to clean things up.

Happy to help set something up.

**Comment by postmodern** [comment]
We could hook rubocop into the `release` task as a "pre-flight check". I'm mainly concerned with checking PRs for bad syntax and getting contributors to fix bad syntax before I have to manually review it or it gets merged prematurely.

**Comment by gurgeous** [comment]
OK, let's start with the CI. We can run rubocop -A manually (via rake or otherwise), and encourage contributors to do the same. Maybe this?

```yaml
name: rubocop
on: [ push, pull_request ]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run rubocop
        run: bundle exec rubocop --parallel
```

**Comment by postmodern** [comment]
@gurgeous looks good to me. What's the standard practice for adding linting to GitHub Actions CI: should it be added to the existing testing workflow, or should a new workflow be created to keep the two separate?

**Comment by gurgeous** [comment]
Not totally sure. It could probably be another job in the same workflow since they share the same properties (`push/pull_request`). Harmless to make it a separate workflow, though.
