### ISSUE TITLE
Add support for ANSI background colors

### ISSUE THREAD

**Issue by postmodern** [postmodern/command_kit.rb#35]
While I tend to not use ANSI background colors, I think the `CommandKit::Colors` module should still support setting the [ANSI background color](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters).

## Proposed Syntax

```ruby
puts Colors.bg_green("hello")
```

Setting both background and foreground colors:

```ruby
puts Colors.bg_green(Colors.white("hello"))
```

`bg_*` color methods and `BG_*` ANSI constants would need to be added, as well as a `bg_reset` / `bg_default` method and `BG_RESET` / `BG_DEFAULT` constant for `\e[49m` which switches the background color back to the terminals default color (where as `reset` / `RESET` clobbers all ANSI attributes).

Also open to alternative naming (`green_bg`? `on_green`?).

**Comment by gurgeous** [comment]
Seems straightforward. Question - is this worth refactoring the color & bg_color methods to use a loop with define_method?

**Comment by postmodern** [comment]
I prefer to manually define methods so they show up in the YARDoc.

**Comment by postmodern** [comment]
Implemented in #37.

**Comment by gurgeous** [comment]
> I prefer to manually define methods so they show up in the YARDoc.

I've often wondered about that. Maybe there is a way? https://stackoverflow.com/questions/39266833/ That would help some of my other projects too

**Comment by postmodern** [comment]
Yeah you have to define a method which does the meta-programming and tag it with `@macro`, but then you have a meta-programming method that is only used in one place.

**Comment by gurgeous** [comment]
Probably not worth the trouble. I was almost ready to write a script to generate those guys, but it was pretty easy with multiple cursors 😛
