### ISSUE TITLE
Reault of `Interactive#ask` contains newline

### ISSUE THREAD

**Issue by fnordfish** [postmodern/command_kit.rb#74]
In https://github.com/postmodern/command_kit.rb/blob/9e04760e401be44f5afbef9bc610cfe8a1138e07/lib/command_kit/interactive.rb#L80 it should probably remove the newline (entered by the user to confirm their input).

As far as I have tested that's why `ask("input", required: true)` does not loop for "empty" inputs, because they'll contain a `\n` cause by the user hitting the return key.

**Comment by postmodern** [comment]
Fixed in 309c63f1f41879151cd6d374855771d17a0cb076. GitHub appears to be having some issues today and didn't auto-close this issue or run GitHub Actions yet.

**Comment by postmodern** [comment]
Fixed in 0.5.3.
